name: LLMOPS CI/CD Pipeline

on:
  push:
    branches:
      - main
permissions:
  id-token: write
  contents: read
jobs:
  # Job 1: Deploy Infrastructure using Bicep
  deploy_infrastructure:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: "Az CLI Login"
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy Bicep template
        run: |
          az deployment group create --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} --template-file aistudio-main.bicep --parameters main.bicepparam

  # Job 2: Upload Data to Index
  upload_data_to_index:
    runs-on: ubuntu-latest
    needs: deploy_infrastructure  # Job 2 depends on Job 1
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: "Az CLI Login"
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Upload data to index
        run: |
          python ./scripts/upload_data_to_index.py

  # Job 3: Run Evaluation
  run_evaluation:
    runs-on: ubuntu-latest
    needs: upload_data_to_index  # Job 3 depends on Job 2
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: "Az CLI Login"
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Run evaluation script
        run: |
          python ./scripts/evaluation.py --evaluation-data-path ./evaluation_data/data.jsonl --evaluation-name evaluationgha --metrics groundedness

  # Job 4: Deploy Model
  deploy_model:
    runs-on: ubuntu-latest
    needs: run_evaluation  # Job 4 depends on Job 3
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: "Az CLI Login"
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Deploy model
        run: |
          python ./scripts/deploy_model.py

  # Job 5: Test Model Deployment
  test_model_deployment:
    runs-on: ubuntu-latest
    needs: deploy_model  # Job 5 depends on Job 4
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: "Az CLI Login"
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Test model deployment
        run: |
          python ./scripts/test_deployment.py --endpoint-name sqd-endpoint --query "what is sqd ?"
